version: "3"
services:
  postgres:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '10thingsloveaboutpg'
      POSTGRES_DB: weather
